name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Get version
      id: version
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          VERSION="1.0.${{ github.run_number }}"
        else
          VERSION="1.0.${{ github.run_number }}-preview"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

    - name: Update version in project
      run: |
        sed -i "s/<Version>1.0.0<\/Version>/<Version>${{ steps.version.outputs.version }}<\/Version>/" demodebcli.csproj
        sed -i "s/<AssemblyVersion>1.0.0<\/AssemblyVersion>/<AssemblyVersion>${{ steps.version.outputs.version }}<\/AssemblyVersion>/" demodebcli.csproj
        sed -i "s/<FileVersion>1.0.0<\/FileVersion>/<FileVersion>${{ steps.version.outputs.version }}<\/FileVersion>/" demodebcli.csproj

    - name: Restore dependencies
      run: dotnet restore

    - name: Build AOT
      run: dotnet publish -c Release --self-contained -r linux-x64 -p:PublishAot=true

    - name: Create package structure
      run: |
        mkdir -p package/usr/bin
        mkdir -p package/usr/share/man/man1
        mkdir -p package/DEBIAN
        
        # Copy binary
        cp bin/Release/net9.0/linux-x64/publish/demodebcli package/usr/bin/
        chmod +x package/usr/bin/demodebcli

    - name: Create man page
      run: |
        cat > package/usr/share/man/man1/demodebcli.1 << 'EOF'
        .TH DEMODEBCLI 1 "$(date +'%B %Y')" "demodebcli ${{ steps.version.outputs.version }}" "User Commands"
        .SH NAME
        demodebcli \- A demo CLI application
        .SH SYNOPSIS
        .B demodebcli
        .RI [ options ]
        .SH DESCRIPTION
        .B demodebcli
        is a demonstration command-line application that prints "Hello, World!" to the console.
        It serves as an example of an AOT-compiled C# application packaged for Debian/Ubuntu systems.
        .SH OPTIONS
        .TP
        .BR \-v ", " \-\-version
        Display version information including build date and time in both UTC and local time zones.
        .SH EXAMPLES
        .TP
        Run the application:
        .B demodebcli
        .TP
        Show version information:
        .B demodebcli --version
        .SH AUTHOR
        Generated with Claude Code
        .SH "SEE ALSO"
        For more information, visit the project repository.
        EOF
        
        # Compress man page
        gzip package/usr/share/man/man1/demodebcli.1

    - name: Create control file
      run: |
        cat > package/DEBIAN/control << EOF
        Package: demodebcli
        Version: ${{ steps.version.outputs.version }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Demo Package <demo@example.com>
        Description: Demo CLI application
         A demonstration command-line application written in C# and compiled
         with AOT (Ahead of Time) compilation for optimal performance.
         .
         This package installs the demodebcli command which prints "Hello, World!"
         and provides version information.
        Depends: libc6 (>= 2.17)
        EOF

    - name: Create postinst script
      run: |
        cat > package/DEBIAN/postinst << 'EOF'
        #!/bin/bash
        set -e
        
        # Update man database
        if command -v mandb >/dev/null 2>&1; then
            mandb -q /usr/share/man
        fi
        
        echo "demodebcli has been installed successfully!"
        echo "You can now run 'demodebcli' from anywhere or 'man demodebcli' for help."
        EOF
        chmod +x package/DEBIAN/postinst

    - name: Create prerm script
      run: |
        cat > package/DEBIAN/prerm << 'EOF'
        #!/bin/bash
        set -e
        
        echo "Removing demodebcli..."
        EOF
        chmod +x package/DEBIAN/prerm

    - name: Create postrm script
      run: |
        cat > package/DEBIAN/postrm << 'EOF'
        #!/bin/bash
        set -e
        
        # Update man database after removal
        if command -v mandb >/dev/null 2>&1; then
            mandb -q /usr/share/man 2>/dev/null || true
        fi
        
        echo "demodebcli has been completely removed."
        EOF
        chmod +x package/DEBIAN/postrm

    - name: Build deb package
      run: |
        dpkg-deb --build package demodebcli_${{ steps.version.outputs.version }}_amd64.deb

    - name: Test package installation
      run: |
        # Install the package
        sudo dpkg -i demodebcli_${{ steps.version.outputs.version }}_amd64.deb || sudo apt-get install -f -y
        
        # Test the binary
        demodebcli
        demodebcli --version
        
        # Test man page
        man demodebcli | head -n 10
        
        # Remove the package to test cleanup
        sudo dpkg -r demodebcli

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Release v${{ steps.version.outputs.version }}
          
          Built on: ${{ steps.version.outputs.build_date }}
          
          ### Installation
          
          Download the `.deb` package and install it:
          
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.version }}/demodebcli_${{ steps.version.outputs.version }}_amd64.deb
          sudo dpkg -i demodebcli_${{ steps.version.outputs.version }}_amd64.deb
          ```
          
          Or add our repository (see README for instructions).
          
          ### Usage
          
          ```bash
          demodebcli              # Print Hello, World!
          demodebcli --version    # Show version info
          man demodebcli          # View manual page
          ```
        files: |
          demodebcli_${{ steps.version.outputs.version }}_amd64.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: demodebcli-deb-package
        path: demodebcli_${{ steps.version.outputs.version }}_amd64.deb