name: Build and Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore & Publish (AOT, linux-x64)
        run: |
          dotnet restore
          dotnet publish -c Release -r linux-x64 /p:PublishAot=true /p:SelfContained=true -o out/publish

      # 👇 YOUR packaging step; ensure a .deb appears under out/pkg/
      # If you already have a script, call it here and leave the mv below.
      - name: Package .deb (placeholder)
        run: |
          mkdir -p out/pkg
          # build your deb here (dpkg-deb / fpm / your script) to out/pkg/
          # ensure filename contains _amd64.deb
          # e.g.: out/pkg/demodebcli_1.0.99_amd64.deb
          test -f out/pkg/*_amd64.deb

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: out/pkg/*_amd64.deb
          if-no-files-found: error
