name: Publish APT repo

on:
  workflow_run:
    workflows: ["Build and Package"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: apt-repo-${{ github.event.workflow_run.id || 'manual' }}
  cancel-in-progress: true

jobs:
  publish:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev xz-utils
          sudo snap install gh || true

      - name: Reset dists/ and layout + .nojekyll
        run: |
          rm -rf dists
          mkdir -p dists/stable/main/binary-amd64
          mkdir -p pool/main/d/demodebcli
          rm -f dists/stable/InRelease dists/stable/Release.gpg || true
          touch .nojekyll

      - name: Download .deb artifact from build
        uses: actions/download-artifact@v4
        with:
          name: deb
          path: incoming
          # available only on workflow_run:
          run-id: ${{ github.event.workflow_run.id }}

      - name: Copy into pool/
        run: |
          cp incoming/*_amd64.deb pool/main/d/demodebcli/
          ls -l pool/main/d/demodebcli/

      - name: Build Packages (must run from repo root)
        run: |
          dpkg-scanpackages -m pool /dev/null > dists/stable/main/binary-amd64/Packages
          gzip -f -9 dists/stable/main/binary-amd64/Packages
          xz   -f    dists/stable/main/binary-amd64/Packages

      - name: Build Release (references main/binary-amd64/*)
        run: |
          cat > release.conf <<'EOF'
          APT::FTPArchive::Release::Suite "stable";
          APT::FTPArchive::Release::Codename "stable";
          APT::FTPArchive::Release::Components "main";
          APT::FTPArchive::Release::Architectures "amd64";
          EOF
          apt-ftparchive -c=release.conf release dists/stable > dists/stable/Release
          echo "=== Sanity ==="
          grep -E '^(Components:|Architectures:)| main/binary-amd64/Packages' dists/stable/Release

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish APT repo"
          branch: gh-pages
          file_pattern: |
            dists/**
            pool/**
            .nojekyll
