name: Update APT repository

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-apt-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev jq
          sudo snap install gh || true
          gh --version

      - name: Make repo folders
        run: |
          mkdir -p repo/pool/main/d/demodebcli
          mkdir -p repo/dists/stable/main/binary-amd64

      - name: Download latest release .deb
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p incoming
          # Download the most recent asset matching pattern
          gh release download --repo "${GITHUB_REPOSITORY}" \
            --pattern 'demodebcli_*_amd64.deb' --dir incoming --clobber
          ls -l incoming
          test -f incoming/demodebcli_*_amd64.deb

      - name: Copy into pool
        run: |
          cp incoming/demodebcli_*_amd64.deb repo/pool/main/d/demodebcli/
          find repo/pool -type f -name "*.deb" -print

      - name: Build Packages indexes
        working-directory: repo
        run: |
          # Paths inside Packages must be relative to repo root, so run here
          dpkg-scanpackages -m pool /dev/null > dists/stable/main/binary-amd64/Packages
          gzip -f -9 dists/stable/main/binary-amd64/Packages
          xz -f -z dists/stable/main/binary-amd64/Packages

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update repository"
          branch: gh-pages
          file_pattern: repo/**
          add_options: "-A"

      - name: Move repo/ to root of gh-pages (if needed)
        run: |
          # If your Pages root is repo/, keep as-is. If root is /, copy outward:
          shopt -s dotglob
          if [ -d repo ]; then
            rsync -a --delete repo/ .
            rm -rf repo
          fi

      - name: Final commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Publish APT repo"
          branch: gh-pages
